AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda Chi

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-handler
      CodeUri: s3://bucket-template-sam/lambda-handler.zip
      Runtime: go1.x
      Tracing: Active
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 3
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          TOKEN: FIXME
      Tags:
        testTag: Yo
    Api:
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"

Outputs:
  ProdDataEndpoint:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
