plan:
    package: ./examples/code
name: example-code
inputs:
    TestCodeDirectory:
        dir:
            path: ./deploy/src
    TestImageDirectory:
        dir:
            path: ./deploy/image_deploy
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTlE1QWovSWJUL3BnTHk0
            UkNjcGp3RDhHdEc2QktFUFFDMTU2M0ljY2lnCnhFSlRkM0hoVFJyank4M0c2OHhh
            aEZIaHFMTUlTa0ZHWW9GM2p4dlN3MjQKLS0tIGN2bVV0RU9yQnBOS05OSGlhc2hn
            ZVQxN0xZdGhoNkhOdW42QjBNckNhYzQKRhi/kpx/TTfVLwvY4XxakL08SvccouUo
            9jjQIGFizwMAaCmd8NPsHfS0GXrXCvMQwEbHQHFnRHPZ7tKrzgw48w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-08-02T13:19:46Z"
    mac: ENC[AES256_GCM,data:gR8icbKTPA5gTG9VUXKYjp68GX6P1ieY/hOkvMoWlKwgaFi/ya5rCJ7x6823ZKZjfBIZIaM0jtHYMLpeQYyqNkAgNEkusWk2izJ/gX+AURoDpN9ZX72u3VOtWR2wRnzPib6HEF2XsKubGhfjDQMHOseVDk6Ss1PB3Qufvcj93QQ=,iv:omJRaCGIWuQZCnTgehhkSK73/8FflAJD/6cd6OBR2gM=,tag:9wCTlkFIxTofT7ME1i9SgA==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
