name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Version Tags
        required: true

jobs:
  release_pkg:
    name: Release package version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/actions-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tags }}
          files: |
            cue.mod/usr/github.com